In [1]:
import nashpy as nash
import numpy as np
import random
from texttable import Texttable


In [2]:
def printPayoffMatrix(game):
    row_matrix = game.payoff_matrices[0]
    column_matrix = game.payoff_matrices[1]
    
    table = Texttable()
    col_str = ['', 'C-X', 'C-Y']
    table.add_row(col_str)
    
    row_strs = ['R-P', 'R-Q']
    for row in range(row_matrix.shape[0]):
        row_str = [row_strs[row]]
        for column in range(row_matrix.shape[1]):
            row_str.append(str(row_matrix[row, column]) + ',' + str(column_matrix[row, column]))
        table.add_row(row_str)
    print(table.draw())
        

In [3]:
#Game 1
R =np.array([[1,2], [2,0]])
C =np.array([[0,1], [0,-1]])

In [9]:
game1 = nash.Game(R, C)
game1
#printPayoffMatrix(game1)

Bi matrix game with payoff matrices:

Row player:
[[1 2]
 [2 0]]

Column player:
[[ 0  1]
 [ 0 -1]]

In [5]:
printPayoffMatrix(game1)

+-----+-----+------+
|     | C-X | C-Y  |
+-----+-----+------+
| R-P | 1,0 | 2,1  |
+-----+-----+------+
| R-Q | 2,0 | 0,-1 |
+-----+-----+------+


In [6]:
#Calculate outcome of a play where both players play pure strategies
sigma_r = ([1,0])
sigma_c = ([0,1])
game1[sigma_r, sigma_c]

array([2, 1])

In [7]:
#Another strategy profile
sigma_r = np.array([1,0])
sigma_c = np.array([1,0])
game1[sigma_r, sigma_c]


array([1, 0])

In [8]:
#Another strategy profile 2 
sigma_r = np.array([0,1])
sigma_c = np.array([0,1])
game1[sigma_r, sigma_c]

array([ 0, -1])

In [ ]:
# A Strategy progile with the row player plaing a mixed strategy, 
sigma_r = np.array([0.5,0.5])
sigma_c = np.array([0,1])
game1[sigma_r, sigma_c ]

In [10]:
#Game 1
R =np.array([[1,2], [2,0]])
C =np.array([[0,1], [0,-1]])

In [11]:
game1 = nash.Game(R, C)
game1
printPayoffMatrix(game1)

+-----+-----+------+
|     | C-X | C-Y  |
+-----+-----+------+
| R-P | 1,0 | 2,1  |
+-----+-----+------+
| R-Q | 2,0 | 0,-1 |
+-----+-----+------+


In [12]:
col_equilibria_strategies =[]
equilibria = game1.support_enumeration()
for eq in equilibria:
    print(eq)
    print(eq[0])
    axo=eq[0]
    dedo= eq[1]
    print(dedo)
    col_equilibria_strategies.append(eq)

number_strats = len(col_equilibria_strategies)
weights_for_strats = 1/number_strats
col_equil_weights = []
for z in range(len(col_equilibria_strategies)):
    col_equil_weights.append(weights_for_strats)

(array([1., 0.]), array([0., 1.]))
[1. 0.]
[0. 1.]
(array([0., 1.]), array([1., 0.]))
[0. 1.]
[1. 0.]
(array([0.5, 0.5]), array([0.66666667, 0.33333333]))
[0.5 0.5]
[0.66666667 0.33333333]


In [14]:
outcomes_r = []
outcomes_c = []

    
print(col_equil_weights)
print(weights_for_strats)
r_action = np.array([1,0])
rounds = 10
for i in range(rounds):
    c_action = random.choices(col_equilibria_strategies, k=1, weights = col_equil_weights) [0]
    print(c_action)
    print(r_action)
    sigma_r = np.array(r_action)
    sigma_c = np.array(c_action)
    print("SIGMA_R: ", sigma_r)
    print("SIGMA_C: ", sigma_c)
    util = game1[sigma_r, sigma_c]
    outcomes_r.append(util[0])
    outcomes_c.append(util[1])
ave_outcome_r = np.mean(outcomes_r)
ave_outcome_c = np.mean(outcomes_c)
print('average outcome r =', ave_outcome_r, ', avg_ouctome_c', ave_outcome_c)
    
    
    
    
    
    

[0.3333333333333333, 0.3333333333333333, 0.3333333333333333]
0.3333333333333333
(array([0., 1.]), array([1., 0.]))
[1 0]
SIGMA_R:  [1 0]
SIGMA_C:  [[0. 1.]
 [1. 0.]]
(array([1., 0.]), array([0., 1.]))
[1 0]
SIGMA_R:  [1 0]
SIGMA_C:  [[1. 0.]
 [0. 1.]]
(array([1., 0.]), array([0., 1.]))
[1 0]
SIGMA_R:  [1 0]
SIGMA_C:  [[1. 0.]
 [0. 1.]]
(array([0.5, 0.5]), array([0.66666667, 0.33333333]))
[1 0]
SIGMA_R:  [1 0]
SIGMA_C:  [[0.5        0.5       ]
 [0.66666667 0.33333333]]
(array([0., 1.]), array([1., 0.]))
[1 0]
SIGMA_R:  [1 0]
SIGMA_C:  [[0. 1.]
 [1. 0.]]
(array([1., 0.]), array([0., 1.]))
[1 0]
SIGMA_R:  [1 0]
SIGMA_C:  [[1. 0.]
 [0. 1.]]
(array([0.5, 0.5]), array([0.66666667, 0.33333333]))
[1 0]
SIGMA_R:  [1 0]
SIGMA_C:  [[0.5        0.5       ]
 [0.66666667 0.33333333]]
(array([1., 0.]), array([0., 1.]))
[1 0]
SIGMA_R:  [1 0]
SIGMA_C:  [[1. 0.]
 [0. 1.]]
(array([0.5, 0.5]), array([0.66666667, 0.33333333]))
[1 0]
SIGMA_R:  [1 0]
SIGMA_C:  [[0.5        0.5       ]
 [0.66666667 0.3333333